title: datamachines
description: ''
author: "Eric Nolette"

theme: minima

# Minima social links
github_username: ericnolette
linkedin_username: enolette

# Minima: show excerpts in the frontpage
show_excerpts: False

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/welcome.md
  - _pages/about.md

include:
  - _pages